# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def available_pods
  pod 'Alamofire', '5.1.0'
  pod 'SVProgressHUD', '2.2.5'
  pod 'SDWebImage', '5.8.1'
end

target 'VaradhiInterviewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	available_pods
  # Pods for VaradhiInterviewDemo

end
